In [8]:
import numpy as np

In [ ]:
class MyRandom(object):
    def __init__(self, seed: int, operation: str ="+", j: int =3, k: int =7, m: int =10):
        assert 0 < j < k
        seed = str(seed)
        assert len(seed) >= k
        
        if operation == "+":
            self.op = lambda x, y : x + y
        elif operation == "*":
            self.op = lambda x, y : x * y
        elif operation == "-":
            self.op = lambda x, y : x - y
        else:
            raise Exception
        
        self.seed = np.fromiter(map(int, seed), dtype=np.int)
        self.j = j
        self.k = k
        self.m = m
    def random(self):
        randint = self.op(self.seed[self.j-1], self.seed[self.k-1]) % self.m
        self.seed = np.append(self.seed[1:], randint)
        return randint
        
        

In [25]:
rand_add = MyRandom(6421893)
for i in range(5):
    print(rand_add.seed, rand_add.random())

[6 4 2 1 8 9 3] 5
[4 2 1 8 9 3 5] 6
[2 1 8 9 3 5 6] 4
[1 8 9 3 5 6 4] 3
[8 9 3 5 6 4 3] 6


In [24]:
rand_mult = MyRandom(6421893, operation="*")
for i in range(5):
    print(rand_mult.seed, rand_mult.random())

[6 4 2 1 8 9 3] 6
[4 2 1 8 9 3 6] 6
[2 1 8 9 3 6 6] 8
[1 8 9 3 6 6 8] 2
[8 9 3 6 6 8 2] 6


In [26]:
rand_sub = MyRandom(6421893, operation="-")
for i in range(5):
    print(rand_sub.seed, rand_sub.random())

[6 4 2 1 8 9 3] 9
[4 2 1 8 9 3 9] 2
[2 1 8 9 3 9 2] 6
[1 8 9 3 9 2 6] 3
[8 9 3 9 2 6 3] 0
